### ISSUE TITLE
Can't seem to run on 1.16.

### ISSUE THREAD

**Issue by Ayria** [AllOfFabric/OLBM#2]
Hey, I downloaded and dropped in the newest update for this mod and I can't get it to run.

Using:
fabric-api-0.4.32+build.296-1.16
olbm-1.0.0+1.15.2
fabric-loader-0.7.8+build.184-20w06a

<details><summary>The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors! **Click to Expand**</summary><p>

---
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2/15/20 1:33 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:399)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoClassDefFoundError: com/swordglowsblue/artifice/api/ArtificeResourcePack$ClientResourcePackBuilder
		at io.github.alloffabric.olbm.OLBClient.onInitializeClient(OLBClient.java:28)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1499/392929911.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:48)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: com.swordglowsblue.artifice.api.ArtificeResourcePack$ClientResourcePackBuilder
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:399)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: Snapshot 20w06a
	Minecraft Version ID: 20w06a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1190662032 bytes (1135 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.4.32+build.296-1.16
		fabric-api-base: Fabric API Base 0.1.2+b7f9825dbf
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.0+b7436ccabf
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea89bf
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825dbf
		fabric-containers-v0: Fabric Containers (v0) 0.1.4+9421522dbf
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825dbf
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825dbf
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.5+9421522dbf
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.8+9421522dbf
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825dbf
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e1bf
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d6bf
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a7305bf
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825dbf
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d6bf
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.4+9421522dbf
		fabric-networking-v0: Fabric Networking (v0) 0.1.8+9421522dbf
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c3bf
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d6bf
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.7+9421522dbf
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+7d8ccbd7bf
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.24+cfa5f8f2bf
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a60bf
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825dbf
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed9bf
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+53410490bf
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+53410490bf
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b3bf
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd91580bf
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba7bf
		fabricloader: Fabric Loader 0.7.8+build.184
		jankson: Jankson 2.0.1+j1.2.0
		minecraft: Minecraft 1.16-alpha.20.6.a
		olbm: OLBM 1.0.0+1.15.2
		staticdata: Static Data 1.1.2
	Launched Version: fabric-loader-0.7.8+build.184-20w06a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

---

Collapsible until here.
</p></details>

**Comment by LemmaEOF** [comment]
oh boy, looks like Artifice isn't loading for some reason.

**Comment by LemmaEOF** [comment]
Ahhh, looks like Artifice requires a `1.15.x` version of Minecraft, and failed silently while resolving dependencies. I'll talk to Fudge about a 1.16 version of Artifice. I'll keep this open till an Artifice version that supports 1.16 is available.

**Comment by Ayria** [comment]
Not sure if you saw, but Fudge said there was one: https://github.com/natanfudge/artifice/tree/1.16

Just in case you didn't see. Thanks!

**Comment by LemmaEOF** [comment]
Alright, nice! I'll make a fork soon.

**Comment by Martmists-GH** [comment]
Any updates on this?

**Comment by LemmaEOF** [comment]
I don't mod anymore and nobody really wants to touch OLBM due to personal ideology but from what I can see it's just a couple-line fix in the build.gradle and a re-build
